// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var x = {
  event: "hel",
  hello_world: "world"
};

var event_ = x.event;

function foo(val) {
  if (val.TAG === /* T1 */0) {
    console.log(val.a + " " + val.b);
  }
  
}

function dog(param_0) {
  return /* Dog */{
          _0: param_0
        };
}

var tommy = /* Dog */{
  _0: "tommy"
};

var x_ = {
  name: "nithin",
  dob: "15/Jun/2000"
};

var e1_ = {
  TAG: /* T1 */0,
  a: "hello",
  b: "world"
};

var e2_ = {
  TAG: /* T2 */1,
  c: "hello",
  d: "world"
};

var cat = /* Cat */0;

exports.x = x;
exports.event_ = event_;
exports.x_ = x_;
exports.e1_ = e1_;
exports.e2_ = e2_;
exports.foo = foo;
exports.dog = dog;
exports.cat = cat;
exports.tommy = tommy;
/* event_ Not a pure module */
