// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function x(string) {
  return string;
}

function hi(string) {
  return string + "F";
}

var Hello = {
  x: x,
  hi: hi
};

exports.Hello = Hello;
/* No side effect */
