// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");

console.log(Js_dict.fromList({
          hd: [
            "hellw",
            0
          ],
          tl: {
            hd: [
              "world",
              2
            ],
            tl: /* [] */0
          }
        }));

var x = {
  name: "nithin",
  email: "ntihin@gmail.com"
};

exports.x = x;
/*  Not a pure module */
