// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

var someArray = [
  1,
  2,
  3,
  4,
  5
];

var increment = Belt_Array.map(someArray, (function (e) {
        return e + 1 | 0;
      }));

var get_opt = Belt_Array.get(someArray, 1);

var a = get_opt !== undefined ? get_opt : -1;

var get_exp = Belt_Array.getExn(someArray, -1);

var set_ = Belt_Array.set(someArray, 1, 9);

exports.someArray = someArray;
exports.increment = increment;
exports.get_opt = get_opt;
exports.a = a;
exports.get_exp = get_exp;
exports.set_ = set_;
/* increment Not a pure module */
