// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var song = new Audio("fs");

song.play();

var a = document.getElementById("root");

var b = document.getElementById("root");

alert("Hello, world!");

console.log(a.isEqualNode(b));

exports.song = song;
exports.a = a;
exports.b = b;
/* song Not a pure module */
